[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_escrow_anchor = "A7Pc9wBYYY9ZhfMNopRha8KmWk8k46ZZfVrwoiYWFbV5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
